### ISSUE TITLE
Clear screen on exit

### ISSUE THREAD

**Issue by ghost** [mdibaiee/node-games#4]
Hi, cool games! I was playing around with it a bit and noticed the screen didn't clear when exiting (on Linux and Windows). I think this isn't wanted behaviour? I think clearing one more time on exit could solve this.

``` javascript
// classes/interface.js
if (key === 'exit') {
  this.output.write('\u001b[2J\u001b[0;0H'); // this through fat arrow function
  process.exit();
}
```

Example: Here you can see a leftover snake :snake: while issuing a new command.

![snakeAfterExit](https://cloud.githubusercontent.com/assets/8117909/13761353/4f078b82-ea38-11e5-887e-5f349e9e1abc.jpg)

**Comment by mdibaiee** [comment]
@verth: Hey! Thanks for the feedback! 👍

See if this branch works on your machine: https://github.com/mdibaiee/node-games/tree/clear-on-exit

You can make a pull-request yourself, too, if you want!

**Comment by ghost** [comment]
Works like a charm for me, thanks @mdibaiee !

Don't think there is a need to make a pull-request?

**Comment by mdibaiee** [comment]
@verth: d3bd75a27773772290e265c4c9a8c0d817977667 Published a new version to npm, thank you!
