### ISSUE TITLE
folder structure looks different

### ISSUE THREAD

**Issue by boddumanohar** [mdibaiee/node-games#6]
you folder structure looks different to other node js projects. Most node js contains has lib, public, router, scripts, views but you are following a different structure. I am curious to know reason for your structure.

**Comment by mdibaiee** [comment]
Well, `public`, `router` and `scripts` are needed when you have a server, there is no server here, so why would I need a `router` or `public` folder?

It's pretty common to use `lib` and `src` interchangeably.

**Comment by boddumanohar** [comment]
@mdibaiee Thanks
